services:
  db:
    image: mysql:8.0
    container_name: library-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: library_db
    ports:
      - "3306:3306"
    volumes:
      #- ./db_data:/var/lib/mysql          # ← persist data here
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - appnet

  backend:
    build: ./backend
    container_name: library-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: library-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:

  #db_data:    # ← named volume for MySQL data
